### ISSUE TITLE
GPU execution

### ISSUE THREAD

**Issue by gabrer** [dallascard/neural_topic_models#1]
Hello,

Thank you for providing your implementation.
Does this implementation run on GPU? If so, how?

Thank you!

**Comment by dallascard** [comment]
At the moment it does not provide support for GPUs. However, I will soon be replacing this repo with one that does (in pytorch). Watch this space!

**Comment by gabrer** [comment]
Thanks for the prompt reply!

**Comment by dallascard** [comment]
Okay, this repo has now been replaced with a newer one at [https://www.github.com/dallascard/scholar](https://www.github.com/dallascard/scholar)

The new repo offers GPU in pytorch.
